--- #YAML:1.0
name:                Email-MIME-Encodings
version:             1.311
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    MIME::Base64:                  3.05
    MIME::QuotedPrint:             3.03
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
