---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-MIME-Encodings
no_index:
  directory:
    - t
    - inc
requires:
  MIME::Base64: 3.05
  MIME::QuotedPrint: 3.03
resources:
  repository: http://github.com/rjbs/email-mime-encodings
version: 1.314
