# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-MIME-Encodings
version:      1.2
version_from: Encodings.pm
installdirs:  site
requires:
    MIME::Base64:                  3.01
    MIME::QuotedPrint:             3.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
